### ISSUE TITLE
LogWatchStreamProcessor keeps collecting output (=using memory) after client is done

### ISSUE THREAD

**Issue by jstuyts** [flapdoodle-oss/de.flapdoodle.embed.process#106]
The `LogWatchStreamProcessor` keeps appending to a string builder for the output after the client has used the processor to get the needed information. This means that for long running processes with lots of output, the processor needlessly consumes a lot of memory.

Add a method to the processor so the client can indicate that it is ready with the processor, and the processor can stop consuming excessive memory.

**Comment by Loki-Afro** [comment]
Looks legit, you can create a PR for that onto the process-2.x.x branch :)
