### ISSUE TITLE
Add custom property to force 64 bit architecture

### ISSUE THREAD

**Issue by FlamingTuri** [flapdoodle-oss/de.flapdoodle.embed.process#117]
[`BitSize`](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/distribution/BitSize.java) detects that my computer has a 32 bit architecture even though it has a 64 bit one. This causes de.flapdoodle.embed.mongo to attempt downloading a wrong mongodb version. As a workaround, I set the value of `os.arch` property to `x86_64` in the main of my application. However, I think it could be useful to add a custom property (which can be specified via command line or via application.properties) to let the user force the the 64 bit architecture if this issue happens.

**Comment by michaelmosmann** [comment]
Does this problem still exist? Which platform do you use?

**Comment by FlamingTuri** [comment]
I was on Kubuntu 20.10. If I remember correctly, I was using a jdk for 32 bit architecture on a 64 bit one. I still think it could be a nice to have feature for future releases if you find yourself in a similar situation

**Comment by michaelmosmann** [comment]
So i can not rely on os.arch for that.. hmm.. interesting.

Thank you:) .. if you have any idea how to solve this, i moved this part into a new lib (https://github.com/flapdoodle-oss/de.flapdoodle.os)
