### ISSUE TITLE
Issues when running on CICD (teamcity)

### ISSUE THREAD

**Issue by mikebell90** [flapdoodle-oss/de.flapdoodle.embed.process#125]
We use flapdoodle for example with postgres and mongo.

Because this runs in a docker container in TC and one where we don't have full rights we repeatedly get failures like

```
cannot move
tmp/embedmongo-download-8d34dfa0-3599-4fa1-9d22-e2b3bb822bd5.TGZ to /home/teamcity/.embedmongo/linux/mongodb-linux-x86_64-4.0.2.tgz
```

Is there a way to force it to /tmp (via ENV VAR or system property - no code) subdir? Whats your advice?

**Comment by michaelmosmann** [comment]
Hmm... i think there could be a way.. the default way of storing downloaded artifacts is inside of the user home directory.
Do you use this library itself or embedded-mongodb for this stuff?

**Comment by mikebell90** [comment]
embedded mongo, sorry for th e late reply.

**Comment by michaelmosmann** [comment]
@mikebell90 one way would be creating a symlink from /home/teamcity./embedmongo to something inside /tmp .. the more complicated one: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-artifact-storage

**Comment by mikebell90** [comment]
Yeah maybe. We switched to Testcontainers, but thanks for the response.

**Comment by michaelmosmann** [comment]
@mikebell90 .. totally fine with that.. i expected that everyone is using testcontainers for this.. 
(but that is not the case.. still >100.000 downloads from maven central each month)
