### ISSUE TITLE
Document IArtifactStore.checkDistribution

### ISSUE THREAD

**Issue by benmccann** [flapdoodle-oss/de.flapdoodle.embed.process#17]
Would you be able to describe what `checkDistribution` is supposed to do? I'm not quite sure how to create an implementation of `IArtifactStore` since there's no Javadoc for this method

**Comment by michaelmosmann** [comment]
I did a lot of refactoring in this are.. and i will do a lot more (rewrite most of it). So i hope, with the next major release it will be much better to understand each piece.. :)
