### ISSUE TITLE
Discussion: support for extraction of directories/folders

### ISSUE THREAD

**Issue by viliusl** [flapdoodle-oss/de.flapdoodle.embed.process#21]
For a library I'm working on there is a need to extract folders with whatever there is. It's my-sql, so there are support/translation/schema init files.

My solution now works like:
1. I have a custom/random path for single extraction (ArtifactStore);
2. I have a NoopNaming to preserve original file names;
3. I have added all required files (100 or so) to IPackageResolver.getFileSet();
4. I manually create needed folders.

So it kinda works, but well it's a hackery and not very convenient when moving across supported versions - fragile.

What I actually need is to be able to define a Folder/Directory in IPackageResolver.getFileSet() so all files would be extracted there preserving directory structure.

My suggestion would be:
1. to add FileType.Directory;
2. update abstract extractor to support it. I know it would suck in sense that abstract extractor would have to scan all archive (would not stop once all required files are matched), but oh well..

Maybe you have a better idea? Do you think I could start working on in and get a pull req ready?

**Comment by chapmbk** [comment]
Has any progress been made on this?

**Comment by michaelmosmann** [comment]
I did some rework ... But i am not sure, how far i got. Lets talk about this next week. I will have a look at it. Maybe it is now easier to implement.

**Comment by viliusl** [comment]
Aha, discussion started. If we would agree on baseline implementation, I could work on it and issue a PR.

@michaelmosmann - would you agree to a solution described above?

**Comment by michaelmosmann** [comment]
Now i know, what i had changed.. The current impl is able to store the extraction result in the same way like the downloaded archive. So extraction is now only done once, which should give a major speedup. If we add support for folders and stuff, it should also work this way. ... I have no better idea than yours. :)

**Comment by viliusl** [comment]
Yes and thing you implemented works like magic - using it already in
https://github.com/wix/wix-embedded-mysql:)

Ok, so once I will have some time I will work on introducing folder support
- just did not want to start working on it without having pre-ok from
maintainers - would be sad to spend time on it and get rejected.



On Wed, Oct 7, 2015 at 9:46 AM, Michael Mosmann <notifications@github.com>
wrote:

> Now i know, what i had changed.. The current impl is able to store the
> extraction result in the same way like the downloaded archive. So
> extraction is now only done once, which should give a major speedup. If we
> add support for folders and stuff, it should also work this way. ... I have
> no better idea than yours. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/21#issuecomment-146093916>
> .
>



-- 

*Vilius Lukošius*

Software Engineer


Cell: +37061111226

33 Didžioji St./ 2 Rudininku St. Vilnius Lithuania

**Comment by michaelmosmann** [comment]
I will not reject contributions... :)
