### ISSUE TITLE
Extracting ZIP binaries on OS X doesn't work reliably

### ISSUE THREAD

**Issue by sazzer** [flapdoodle-oss/de.flapdoodle.embed.process#24]
I'm trying to make use of the [PostgreSQL Embedded](https://github.com/yandex-qatools/postgresql-embedded) library that itself uses this library, and on Linux it now works great. Unfortunately on OS X it fails to extract the binaries to execute.

I've raised an issue on the PostgreSQL Embedded issue tracker at https://github.com/yandex-qatools/postgresql-embedded/issues/2, but from investigation it seems that the bug is actually in this library instead.

**Comment by michaelmosmann** [comment]
Will try to make a new release soon.. thanks for your help.

**Comment by sazzer** [comment]
No problem. It's a great project that really makes life easier and safer
for testing so I'm glad to be able to help :-)
