### ISSUE TITLE
Threads/Executor don't get cleaned-up in sbt test

### ISSUE THREAD

**Issue by kfowler** [flapdoodle-oss/de.flapdoodle.embed.process#29]
Our test suite fails when using flapdoodle to run an embedded mongo in our sbt test suite.

It looks like every test creates a new flapdoodle mongo, each of those has a `CachingArtifactStore`, and it creates an executor in its constructor. If I close-out the executor in `CacheCleaner`, our test suite completes successfully. 

Here'a patch: https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/28

**Comment by michaelmosmann** [comment]
ah.. should be fixed. :)
