### ISSUE TITLE
Upgrade commons-compress

### ISSUE THREAD

**Issue by vbauer** [flapdoodle-oss/de.flapdoodle.embed.process#33]
A lot of changes (bug fixes and performance improvements) in commons-compress: https://commons.apache.org/proper/commons-compress/changes-report.html

Could you please upgrade this library from version 1.3 to 1.10?

**Comment by michaelmosmann** [comment]
Sure we can.. (I hope so).. If you want, you can make a pull request:) .. I can change this not before next monday.

**Comment by vbauer** [comment]
NP, I've just sent PR.
