### ISSUE TITLE
de.flapdoodle.embed.process don't include the license file

### ISSUE THREAD

**Issue by puntogil** [flapdoodle-oss/de.flapdoodle.embed.process#42]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by michaelmosmann** [comment]
I added a LICENSE file, but i am not sure, if it is what you wanted... Can you have a look?

btw: why do we need support some fedora packaging stuff? can you explain this a little bit?

**Comment by puntogil** [comment]
hi
that is a "NOTICE" file obtainable at the bottom of the "LICENSE" file available at http://www.apache.org/licenses/LICENSE-2.0.txt
but i found another problem, off topic, our builders haven't a web connection
and this library download, for us [1], unneeded resources [2] (i used an x32 OS). 
thanks
regards
[1] https://fedoraproject.org/wiki/Fedora_Project_Wiki
[2] phantomjs-1.8.2-linux-x86_64.tar.bz2, ...
     https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#No_inclusion_of_pre-built_binaries_or_libraries

**Comment by puntogil** [comment]
if someone uses this library, perhaps, it is why he installed on your operating system  that the package [1] is downloaded ...? otherwise it would not make much sense to me at least ...
sorry for the noise

 [1] mongodb-linux-i686-3.2.1.tgz

**Comment by michaelmosmann** [comment]
Hmm.. If you build this package with maven with enables test, then there is a test which tries to download phantomjs .. 
I can change the project setup, where no integration tests are run by default and this way no download is triggered..
Will that help?

(i did change the LICENSE file.. this time it should be alright)

**Comment by puntogil** [comment]
yes, thanks

**Comment by michaelmosmann** [comment]
btw: why do you build this project yourself and do not use the release-version from maven-central? 
https://repo1.maven.org/maven2/de/flapdoodle/embed/de.flapdoodle.embed.process/

**Comment by puntogil** [comment]
Sorry, again off topic, we use gradle >= 2.5 and for this one is necessary provide a settings.gradle file with the following content:
rootProject.name="de.flapdoodle.embed.process"
the reasons of this request are explained here
https://discuss.gradle.org/t/rootproject-name-in-settings-gradle-vs-projectname-in-build-gradle/5704/2
I used for fix: echo 'rootProject.name="de.flapdoodle.embed.process"' >> settings.gradle

**Comment by puntogil** [comment]
because of our packaging guideline [1]. We can't use pre-built libraries
and binaries. usually we ship in Fedora the latest version of each projects which we use, and all of these are built from source code. the reason/s is/are explained here
[1] https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#No_inclusion_of_pre-built_binaries_or_libraries

**Comment by michaelmosmann** [comment]
Ok.. can we somehow detect,if the project is build for fedora? so we can disable integration test (to prevent downloads). 

Do you use the latest release version or do you build from master (which is not the latest stable version)?

**Comment by matlockx** [comment]
gradle.settings added

**Comment by puntogil** [comment]
for reason of time i used  an x86_64 (but are available for x32, arm) builder
all log file are available here: http://koji.fedoraproject.org/koji/taskinfo?taskID=14519212

**Comment by puntogil** [comment]
Sorry, forgotten, i used latest stable release

**Comment by puntogil** [comment]
no i prefer use maven (ant) instead of gradle ...
