### ISSUE TITLE
Allow AbstractProcess to call Process#destroyForcibly

### ISSUE THREAD

**Issue by bobtiernay-okta** [flapdoodle-oss/de.flapdoodle.embed.process#51]
For daemon processes that don't have application support for a graceful shutdown, there is currently no way to issue a shutdown cleanly in `AbstractProcess` subclasses by calling `stopProcess`:

```java
    @Override
    protected void stopInternal() {
        stopProcess();
    }
```

without the following message being emitted from `ProcessControl#waitForProcessGotKilled`:

> Something bad happend. We couldn't kill <name> process, and tried a lot.
> If you want this problem solved you can help us if you open a new issue.
> 
> Follow this link:
> https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues
> 
> Thank you:)

Note that calling `sendTermToProcess`, `sendKillToProcess` or `tryKillToProcess` inside `stopInternal` doesn't seem to stop the process (at least on MacOS X).

To work around this, I have done the following in my `AbstractProcess` subclass:

```java
    @Override
    protected void stopInternal() {
        try {
            // Hacky, but needed to avoid misleading error message from waitForProcessGotKilled:
            ProcessControl processControl = (ProcessControl) readField(this, "process", true);
            Process process = (Process) readField(processControl, "process", true);
            process.destroyForcibly();
        } catch (IllegalAccessException e) {
            propagate(e);
        }
    }
```

One solution is to expose a new method `destroyForcibly`. Another is to expose the `Process`. Finally, if `waitForProcessGotKilled` could be modified to handle this case, that would probably be best.

**Comment by michaelmosmann** [comment]
Is this still an issue?
