### ISSUE TITLE
Allow logWatch configurable timeout

### ISSUE THREAD

**Issue by gsugambit** [flapdoodle-oss/de.flapdoodle.embed.process#54]
This library has been absolutely amazing. The one problem we have is the isProcessRunning method right now uses a 2000ms timeout and if it does not complete within that time period it returns a false. This causes any conditional logic on this to execute even when the process is really still running.

Could you provide a 

isProcessRunning(Platform platform, long pid, long timeout) and use the timeout value rather than the hard coded 2000ms?

I could actually create a pull request and complete this if needed. IDK the rules on adding functionality here

**Comment by Loki-Afro** [comment]
Would be happy about a PR ;)

**Comment by gsugambit** [comment]
Ok, sounds good. 

The process here is fork, fix in my repo. Then create pull request?

**Comment by Loki-Afro** [comment]
correct

**Comment by gsugambit** [comment]
@Loki-Afro there are a few ways to solve this staying backwards compatible with current code. I can easily do whichever strategy you would like.

1. create a static TIMEOUT parameter (default value to 2000) that can be set and changed and have the current isProcessRunning code use that variable on line 172

e.g. to configure it you would do Processes.TIMEOUT = x.
2. copy and paste the current method, add "timeout" as a parameter and use that.
Drawback to option 1 is loss of ability to change timeout for different calls to the isProcessRunning method
Drawbacks to option 2 is duplicate code.

**Comment by Loki-Afro** [comment]
Hold it backward compatible by overloading the method and there should also be a way for unix like systems, but there I don't know a better way ...

**Comment by gsugambit** [comment]
Lol I'm completely not thinking. Will do

**Comment by gsugambit** [comment]
@Loki-Afro which branch should I work off of? It seems the master branch does not compile but the java8 branch does. In the master there are some missing immutables imports it seems?

**Comment by Loki-Afro** [comment]
process-2.x.x should be the correct version for what you want to do

**Comment by gsugambit** [comment]
@Loki-Afro thanks!

**Comment by gsugambit** [comment]
@Loki-Afro should i be building this on linux? on windows when i do a "mvn clean install", i get a "Cannot run program...CreateProcess error=193, %1 is not a valid Win32 application" exception. Is there some other maven goal or some -D I need to be injecting into the build? 
i looked at the above link and i see it's doing "mvn test" which doesnt work with me either

**Comment by Loki-Afro** [comment]
@gsugambit sorry I do not have a video game console operating system, dunno.

@michaelmosmann can you help?

**Comment by gsugambit** [comment]
@Loki-Afro it seems as if windows doesn't matter in this. I get the same exception on ubuntu except the maven build succeeds
![image](https://user-images.githubusercontent.com/13861767/27890606-66c0136c-61b9-11e7-9d1a-49b575a5cfa4.png)
