### ISSUE TITLE
AbstractProcess.stop : cleanupInternal is not called if stopInternal throws Exception

### ISSUE THREAD

**Issue by faizan-talena** [flapdoodle-oss/de.flapdoodle.embed.process#61]
AbstractProcess.stop calls stopInternal and cleanupInternal.
If stopInternal throws exception should cleanupInterval be called ? Maybe in a finally block ?

This will solve lot of problems where temporary directories are not cleaned up.

**Comment by Wawrzyniec-Nowak** [comment]
I agree. It happened for me as well and temp dirs are not cleaned up which forces to create workarounds like cleaning temp directories inside the application/tests instead of in the library.

**Comment by michaelmosmann** [comment]
@Wawrzyniec-Nowak can you describe your setup?

**Comment by michaelmosmann** [comment]
@faizan-talena there will be a new release .. thanks for this hint:)

**Comment by michaelmosmann** [comment]
Reopen if needed..
