### ISSUE TITLE
TGZ hardlinks are ignored and instead files with size 0 are created

### ISSUE THREAD

**Issue by sasavilic** [flapdoodle-oss/de.flapdoodle.embed.process#70]
Hi,

I was debugging strange issue with embedded Postgres (which internally uses this library) and I found that this library is ignoring hard links from TGZ. Instead of creating hard links, it creates files with size 0.

The problem is at AbstractExtractor::extract(). TarArchiveInputStream returns TarArchiveEntry with following properties:
```
name = "pgsql/share/timezone/Etc/UTC"
linkName = "pgsql/share/timezone/Zulu"
size = 0
```
which is then casted to ArchiveEntry object (variable entry) and by doing that the information about linkName is lost. Further, Apache library will return stream of size 0, thus the end result is empty file instead hard link.

I am not sure if this is issue with this library (not handling special case) or with apache compress (giving back file stream with size 0).

**Comment by sasavilic** [comment]
I am not sure in which library is the problem at, apache compress or this library. Anyway, I found a workaround: I have repacked postgres tgz to remove hard links.

**Comment by Loki-Afro** [comment]
so this issue can be closed? ;)

**Comment by sasavilic** [comment]
Not really :). The issue is still present and workaround is just a workaround.

**Comment by michaelmosmann** [comment]
Is this still an issue?

**Comment by sasavilic** [comment]
I honestly don't know, we are not using this library any more.

**Comment by michaelmosmann** [comment]
@sasavilic  ok.. as i do a lot of refactoring i close this ticket. thanks:)
