### ISSUE TITLE
Q: Is it possible to embed a Java based program with this tool?

### ISSUE THREAD

**Issue by torsten-liermann** [flapdoodle-oss/de.flapdoodle.embed.process#86]
Hi,

Is it possible to embed a Java based program (i.e. fat jar) with this tool without packaging a jdk? All listed projects based on executable binaries.

Thanks,
Torsten

**Comment by torsten-liermann** [comment]
It looks like that is not supported. If I use a bat script as wrapper on Windows 10, the flapdoodle.embed.process logic will not be able to terminate the wrapper process and the java process.

**Comment by Loki-Afro** [comment]
@torsten-liermann no it is not supported. But you ma y had the right guess: repacking the binary with a jdk/jre.
