### ISSUE TITLE
Support for Java newer than 9

### ISSUE THREAD

**Issue by silmeth** [flapdoodle-oss/de.flapdoodle.embed.process#91]
Currently the [`de.flapdoodle.embed.process.runtime.Processes`](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/runtime/Processes.java#L57-L65) class depends on the `javax.lang.model.SourceVersion` enum providing the `RELEASE_9` variant in its `latest()` method to determine whether old legacy way of obtaining `pid` is to be used, or a new one (`pid()` method in `java.lang.Process` class).

It fails on Java 10 and newer, as those provide `RELEASE_10` and `RELEASE_11` respectively. On those new JDKs (and Java 10 is now stable, and Java 11 is going to be released soon) the `Processes` class chooses the legacy path and fails to find the process id on Linux with:

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2370)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
…
```

**Comment by Loki-Afro** [comment]
@silmeth take a look at branch process-2.x.x, which is newer than the master and also production ready (at least the release versions ;) )

**Comment by silmeth** [comment]
Oups, sorry I bothered you then. Thanks for such quick reply! :)
