### ISSUE TITLE
Upgrade commons-compress (once more)

### ISSUE THREAD

**Issue by jawi** [flapdoodle-oss/de.flapdoodle.embed.process#92]
The recently released commons-compress v1.18 includes fixes for the [Zip-slip](https://github.com/snyk/zip-slip-vulnerability) vulnerability. Both the 2.2.x branch as well as master stil use an outdated version making this library potentially vulnerable to Zip-slip.

**Comment by Loki-Afro** [comment]
@jawi thanks for letting us know ;)
