### ISSUE TITLE
Mongo with Postgress test makes terribly slow

### ISSUE THREAD

**Issue by x-hovo-x** [flapdoodle-oss/de.flapdoodle.embed.process#98]
Hi guys,

we are using your lib for embedded mongodb and postgres integration test and if mongo test starts before then postgres takes ages (about 30-40 min) to extract postgresql-9.6.2-1-osx-binaries.zip. (Extract /Users/hasatryan/.embedpostgresql/postgresql-9.6.2-1-osx-binaries.zip START).
If we force to change order then it is perfectly okay. 
We also do profiling and there are 2 threads but no blocking.
Is there anything we have to consider/change?

**Comment by x-hovo-x** [comment]
adding .cmdOptions(new MongoCmdOptionsBuilder()
                        .defaultSyncDelay()
helped for me, any idea why it is 0 in the library?

**Comment by Loki-Afro** [comment]
@x-hovo-x I can only guess, this change was back in 2013.

But with my experience .. syncDelay and mac os or mac os in general and syncing files to disk is a bit weird from time to time.

Not quite sure whats the issue in those cases, maybe it has something to do with the file system as well.

If you can debug further, you could look deeper on os level or fs level...

But does this only affect your mac os tests? just for clarification ;)

**Comment by x-hovo-x** [comment]
Actually, it affects all mac and ubuntu os. 
Moreover, we found out that with de.flapdoodle.embed:de.flapdoodle.embed.mongo:1.50.5 version (Mongo 3.2) works ok but after updating to de.flapdoodle.embed:de.flapdoodle.embed.mongo:2.2.0 (mongo > 3.6) problem appears.

**Comment by Loki-Afro** [comment]
Is 4.x also affected?
Could you provide some source code to reproduce this issue? I know its a lot of work to get such things together but often the only way :/

**Comment by x-hovo-x** [comment]
https://github.com/x-hovo-x/flapdoodle-test

**Comment by Loki-Afro** [comment]
before digging any further I spotted `compile 'cz.jirutka.spring:embedmongo-spring:1.3.1'` this is somewhat deprecated

Please read this issue https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/260 maybe there are some hints for you too.

Could you refactor that out and try again?

**Comment by x-hovo-x** [comment]
sorry, it was copy-paste issue :), I removed it and problem is still there

**Comment by Loki-Afro** [comment]
@x-hovo-x the project has no new commits :/

**Comment by x-hovo-x** [comment]
sorry, pushed ...

**Comment by michaelmosmann** [comment]
Is this still an issue?
